# Project information
site_name: nlp2go
site_description: 🏃 hosting nlp models in one line
site_author: Voidful
site_url: https://github.com/voidful/nlp2go
repo_name: nlp2go
repo_url: https://github.com/voidful/nlp2go
copyright: Copyright &copy; Voidful

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
#  - Models hub: models_hub.md
#  - Class: class.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("docs")
      watch:
        - nlprep

theme:
  name: material
  language: en
  palette:
    primary: blue grey
    accent: blue grey
  font:
    text: Roboto
    code: Roboto Mono
  logo: img/nlp2go-icon.png
  favicon: img/nlp2go-icon.png

# Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/voidful/nlp2go
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/voidful_stack
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/voidful/

# Google Analytics
google_analytics:
  - UA-127062540-3
  - auto

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
   # - pymdownx.highlight:
   #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
